import React, { useState, useEffect } from 'react';
import type { UserInfo } from '../types';

interface DisclaimerPageProps {
  onAgree: (userInfo: Omit<UserInfo, 'role'>) => void;
}

const DisclaimerPage: React.FC<DisclaimerPageProps> = ({ onAgree }) => {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [agreed, setAgreed] = useState(false);
  const [isFormValid, setIsFormValid] = useState(false);

  useEffect(() => {
    const isValidEmail = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
    setIsFormValid(isValidEmail && agreed && name.trim() !== '');
  }, [name, email, agreed]);
  
  const handleContinue = () => {
    if (isFormValid) {
      onAgree({ name, email });
    }
  };

  return (
    <div className="min-h-screen bg-gray-900 text-gray-100 flex items-center justify-center p-4">
      <div className="w-full max-w-2xl bg-gray-800 p-8 rounded-lg shadow-2xl border border-gray-700">
        <h1 className="text-3xl font-bold text-brand-secondary mb-4 text-center">Welcome to the Accounting Financial Centre <span className="ml-2 text-xs align-middle font-semibold text-yellow-300 bg-yellow-900/50 border border-yellow-500 rounded-full px-2 py-1">BETA</span></h1>
        
        <div className="text-left text-gray-300 space-y-4 my-6 border-b border-gray-700 pb-6 text-sm">
            <p>
                This is a specialized hub dedicated to AI-driven financial health assessment and strategic business turnaround. Our core methodology is built upon the proven Altman Z-Score model, enabling a rigorous analysis of your company's Profit & Loss, Balance Sheet, and Cash Flow statements to accurately predict financial distress risk. This is combined with Dr. Teng's turnaround methodology as well as insights from the 8 centres of excellence. Our platform is designed for clarity and action. Simply upload or paste your financial statements, and our AI will generate a precise risk score, a detailed diagnostic report, and a set of actionable, multi-phase recommendations. We uniquely integrate our financial analysis with strategic insights from other specialist centres—covering operations, leadership, marketing, and more—to provide a truly holistic turnaround plan. This comprehensive approach empowers small and medium enterprises to proactively manage financial risks, accelerate recovery, and build a resilient foundation for future growth.
            </p>
        </div>

        <div className="text-left text-gray-300 space-y-4 my-6">
          <h2 className="text-xl font-semibold text-white">Disclaimer and Terms of Use</h2>
          <ul className="list-disc list-inside text-sm space-y-2">
            <li>The analysis provided is for informational and educational purposes only and is generated by an AI.</li>
            <li>It should not be considered professional financial, legal, or investment advice.</li>
            <li>The Altman Z-Score and other models used have limitations and are not guaranteed to be accurate or predictive of future performance.</li>
            <li>We are not liable for any decisions made based on the information provided by this tool. Please consult with qualified professionals before making any financial decisions.</li>
          </ul>
        </div>

        <div className="space-y-4 my-6">
            <input
              type="text"
              placeholder="Your Name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              className="w-full bg-gray-700 border border-gray-600 rounded-md shadow-sm py-2 px-3 text-white focus:outline-none focus:ring-2 focus:ring-brand-secondary"
              aria-label="Your Name"
              required
            />
            <input
              type="email"
              placeholder="Enter your email address"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="w-full bg-gray-700 border border-gray-600 rounded-md shadow-sm py-2 px-3 text-white focus:outline-none focus:ring-2 focus:ring-brand-secondary"
              aria-label="Email Address"
              required
            />
            <div className="flex items-center">
              <input
                id="agree-checkbox"
                type="checkbox"
                checked={agreed}
                onChange={(e) => setAgreed(e.target.checked)}
                className="h-4 w-4 text-brand-secondary bg-gray-700 border-gray-600 rounded focus:ring-brand-secondary"
              />
              <label htmlFor="agree-checkbox" className="ml-2 block text-sm text-gray-300">
                I have read and agree to the terms of use.
              </label>
            </div>
        </div>

        <button
          onClick={handleContinue}
          disabled={!isFormValid}
          className="w-full bg-brand-secondary hover:bg-blue-500 text-white font-bold py-3 px-6 rounded-lg text-lg transition duration-300 ease-in-out transform hover:scale-105 disabled:bg-gray-600 disabled:cursor-not-allowed disabled:transform-none"
        >
          Agree & Continue
        </button>
      </div>
    </div>
  );
};

export default DisclaimerPage;